---

- name: Ensure download folders
  become: True
  file: 
    state: directory
    path: "{{ kafka_tarball_location }}"


- name: Ensure install folders
  become: True
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: 0755
  with_items:
    - "{{ kafka_conf_dir }}"
    - "{{ kafka_data_dir }}"
    - "{{ kafka_log_dir }}"
    - "{{ kafka_app_dir }}"



- name: Fetch kafka binary package
  become: True
  get_url:
    dest: "{{ kafka_tarball_location }}/kafka_{{ kafka_version_scala }}-{{ kafka_version_kafka }}.tgz"
    url: "{{ kafka_apache_mirror }}/kafka/{{ kafka_version_kafka }}/kafka_{{ kafka_version_scala }}-{{ kafka_version_kafka }}.tgz"

- name: Uncompress the kafka tar
  become: True
  become_user: {{ kafka_user }}
  unarchive:
    copy: no
    creates: "{{ kafka_deploy_dir }}/kafka_{{ kafka_version_scala }}-{{ kafka_version_kafka }}"
    dest: "{{ kafka_deploy_dir }}"
    src: "{{ kafka_tarball_location }}/kafka_{{ kafka_version_scala }}-{{ kafka_version_kafka }}.tgz"

- name: Link kafka to the right version
  become: True
  file:
    path: "{{ kafka_app_dir }}"
    src: "{{ kafka_deploy_dir }}/kafka_{{ kafka_version_scala }}-{{ kafka_version_kafka }}"
    state: link

- name: link config dir
  become: True
  file:
    force: yes
    path: "{{ kafka_conf_dir }}"
    src: "{{ kafka_app_dir }}/config"
    state: link

- name: create systemd config
  become: True
  template: dest=/etc/systemd/system/kafka.service owner=root group=root mode=644 src=kafka.service.j2
  notify:
    - restart kafka

# - name: Create Kafka service
#   become: True
#   template:
#     dest: "{{ kafka_upstart_conf }}"
#     owner: root
#     mode: 0644
#     src: kafka.conf.j2
#   notify:
#     - restart kafka
    
- name: Ensure Kafka runs on boot
  become: True
  service:
    enabled: yes
    name: kafka
