---

# Needed to ensure some services start properly
# - name: Set hostname
#   become: True
#   lineinfile:
#     dest: /etc/hosts
#     line: "127.0.0.1 {{ ansible_hostname }}"
#   notify:
#     - restart kafka



- name: Create log4j.properties
  become: True
  template:
    dest: "{{ kafka.conf_dir }}/log4j.properties"
    mode: 0644
    owner: {{ kafka.user }}
    group: {{ kafka.group }}
    src: log4j.properties.j2
  notify:
    - restart kafka

- name: Create server.properties
  become: True
  template:
    dest: "{{ kafka.conf_dir }}/server.properties"
    mode: 0640
    owner: {{ kafka.user }}
    group: {{ kafka.group }}
    src: server.properties.j2
  notify:
    - restart kafka

- name: Ensure Kafka is running
  become: True
  service:
    name: kafka
    state: started
    
- name: Flush handlers to ensure Kafka is up to date
  meta: flush_handlers

- name: Wait for Kafka port
  wait_for:
    port: "{{ kafka.port }}"
    state: started
    timeout: 120
