---

# Needed to ensure some services start properly
# - name: Set hostname
#   become: True
#   lineinfile:
#     dest: /etc/hosts
#     line: "127.0.0.1 {{ ansible_hostname }}"
#   notify:
#     - restart kafka



- name: Create log4j.properties
  become: True
  template:
    dest: "{{ kafka_conf_dir }}/log4j.properties"
    mode: 0644
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    src: log4j.properties.j2
  notify:
    - Reload systemctl daemon
    - restart kafka

- name: Create server.properties
  become: True
  template:
    dest: "{{ kafka_conf_dir }}/server.properties"
    mode: 0640
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    src: server.properties.j2
  notify:
    - Reload systemctl daemon
    - restart kafka

- name: Enable kafka service
  service: name=kafka enabled=yes


# - name: Ensure Kafka is running
#   become: True
#   service:
#     name: kafka
#     state: started
    
- name: Flush handlers to ensure Kafka is up to date
  meta: flush_handlers


- name: Add Kafka binaries to PATH
  template:
    dest: "/etc/profile.d/kafka.sh"
    mode: 0644
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    src: kafka.sh.j2

- name: Wait for Kafka port
  wait_for:
    port: "{{ kafka_port }}"
    state: started
    timeout: 20
