---

- name: Reload systemctl daemon
  become: True
  command: systemctl daemon-reload

- name: start kafka
  become: True
  service:
    name: kafka
    state: started

- name: stop kafka
  become: True
  service:
    name: kafka
    state: stopped

- name: restart kafka
  become: True
  service:
    name: kafka
    state: restarted
