#!/bin/bash

KAFKA="/home/kafka"
BIN="$KAFKA/bin"

PIDS=$(ps ax | grep -i 'kafka\.Kafka' | grep java | grep -v grep | awk '{print $1}')

if [ -z "$PIDS" ]; then
  echo "No kafka server to stop"
  exit 1
else 
  /bin/bash $BIN/kafka_maintenance
  kill -s TERM $PIDS
fi
